linters:
  enable:
    # default
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # added
    - typecheck
    - stylecheck
    - unconvert
    - goconst
    - gofmt
    - unparam
    - nakedret
    - prealloc
    - copyloopvar
    - gocritic
    - revive
    - gocyclo
    - funlen
  disable:
    - errcheck

issues:
  exclude:
    - should not use built-in type string as key
    - should not use basic type string as key in .*

  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - funlen

  exclude-dirs:
    - (^|/)vendor($|/)
  exclude-dirs-use-default: false

run:
  build-tags:
    - db
    - integration
  tests: true
