name: 'Push to master branch'
on:
  push:
    branches:
     - master
  pull_request:

jobs:
  build:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - run: go test ./...