name: 'Build tag'
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'
jobs:
  build:
    name: 'Build and release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: 'Build git-semver'
        run: go build -o git-semver cmd/git-semver
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./git-semver
          asset_name: git-semver
          asset_content_type: application/octet-stream